name: rssreader
version: '0.1' 
summary: This is a rssreader snap application
description: |
  This is a rsssreader snap app which shows how to snap a click Qt app

grade: stable 
confinement: strict

apps:
  rssreader:
    command: desktop-launch rssreader
    plugs: [network,network-manager,unity7,opengl]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  qt-app:    
    source: .
    plugin: qmake
    qt-version: qt5 
    prime:  
      - -usr/share/doc  
      - -usr/include
    after: [desktop-ubuntu-app-platform]
    install: |
      # Create directory to serve as mount point for ubuntu-app-platform
      mkdir $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform 

